version: '3'
services:
  app:
    image: 'disqo-demo'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: 'postgres:11'
    container_name: db
    environment:
      - POSTGRES_DB=demodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password